### ISSUE TITLE
Incorrect path to support projects in STUN solution

### ISSUE THREAD

**Issue by anders9ustafsson** [forestrf/stun#1]
When cloning this repository as-is, the paths to the support projects *BBuffer*, *HashUtils* and *NoGcSockets* and their unit test counterparts are incorrect in the STUN solution file, resulting in these projects not being loaded by the solution.

Apparently the paths in the solution expect the support projects being present in the parent folder rather than as sub-folders of the *stun* folder.

**Comment by forestrf** [comment]
I didn't notice that. It should be fixed now, please let me know if it really works now

**Comment by anders9ustafsson** [comment]
Looks good now. Thanks!
